### ISSUE TITLE
Old videos in 'Screencasts recorded using the latest development versions of darktable' list

### ISSUE THREAD

**Issue by kofa73** [darktable-org/dtorg#101]
https://www.darktable.org/resources/ lists 'Robert Hutton’s darktable screencast playlist' as 'Screencasts recorded using the latest development versions of darktable'; however, his youtube playlist https://www.youtube.com/playlist?list=PLmvlUro_Up1NBX7VK8UUuyWo1B468zEA0 has not been updated since 2016.

- Maybe his videos should appear under a different section, something like 'Screencasts recorded using an older version of darktable'.
- Other relevant videos, e.g. Boris Hajdukovic's 'Editing moments with darktable' (
https://www.youtube.com/watch?v=vnkphET6pYk&list=PLmZmCIhOC2Frt6Wq3gc0-egOy_P1sXjau
) could be added to the section of videos based on a recent darktable version.

**Comment by paperdigits** [comment]
I've cleaned up this page. Please close this issue if you think the clean up is sufficient.

**Comment by kofa73** [comment]
I think the 'Editing moments with darktable' videos would be worth mentioning, especially given Boris's effort lately to produce tutorial-style videos.
But I guess everyone has some favourite. :)
