### ISSUE TITLE
CSS tweaking for top menu

### ISSUE THREAD

**Issue by mpaglia0** [darktable-org/dtorg#110]
It will be more comfortable if the top menu on pages will remain visible while scrolling down contents.

**Comment by patdavid** [comment]
It's something we could consider.  
I'm not personally a fan of fixed top menus but I understand some people would like them. (It takes up vertical space with what I view as secondary importance links.)
Is anything in the top menu so important that you couldn't scroll to the top to access it?

**Comment by mpaglia0** [comment]
Nothing so important. I think it is simply comfortable (mainly when the page content is a very long article). In the past I suggested also to put a GO TO TOP button at the bottom of pages. This can do the same job

**Comment by mpaglia0** [comment]
Issue closed
