### ISSUE TITLE
Update articles to new material

### ISSUE THREAD

**Issue by johnny-bit** [darktable-org/dtorg#119]
In Issue https://github.com/darktable-org/darktable/pull/7123 @floemker referenced article https://github.com/darktable-org/dtorg/blob/master/content/blog/2012-10-23-whats-involved-with-adding-support-for-new-cameras/2012-10-23-whats-involved-with-adding-support-for-new-cameras.md which in turns reffer old script.

Can the article be changed to link to current resources in the header notice? I mean - reference https://github.com/darktable-org/darktable/wiki/Camera-support :)

**Comment by paperdigits** [comment]
Updated that page with a link to the wiki at the top of the article.
