### ISSUE TITLE
Third party packages and PPA don't work for Ubuntu 20.04 - Documentation page needs update

### ISSUE THREAD

**Issue by ocumo** [darktable-org/dtorg#122]
The [darktable.org/install/#3rdparty](https://www.darktable.org/install/#3rdparty) section, documents the existence of third party packages and PPAs for various Ubuntu versions, including **Ubuntu 20.04 LTS**. However, the offered "[latest release](https://software.opensuse.org/download.html?project=graphics:darktable&package=darktable)" and "[master](https://software.opensuse.org/download.html?project=graphics:darktable:master&package=darktable)" PPAs and binaries for Ubuntu 20.04 **_do not work_** because of a series of severe dependency conflicts and problems that cannot be solved by simple installation of missing packages.

Important: _This issue is not about troubleshooting those installation resources._

In spite of darktable.org not being the developer of those resources, and regardless of whether those issues are or are not going to be solved and by whom, the darktable.org documentation is referencing that [wrong] information, thus it's (like it or not) bound to it. The site is naturally seeked as a reference, and expected be curated to at least exclude bad information when detected. Therefore, that section needs an urgent update by removing "Ubuntu 20.04" from the list of supported installation by those specific resources, until and if they ever get corrected or replaced by any demonstrably working resources.

One _possible_ alternative could be modifying the wording of the page to make it (currently it is not) _very_ explicit that DT.org does not maintain, test or endorse any claims made by any third party resources listed in the page.

However: unfortunately, it is also true that such honest wording in the document implies and provokes a sense of distrust to whomever is seeking it for good source of documentation. That would lower the level of usefulness and trustability to that of any random online blog offering a "How To Install", which makes this a very bad idea for a serious project: Nobody goes to e.g. https://developer.mozilla.org to look for a reference that "may or may not" be correct.

Furthermore, I would suggest that any third parties that would like to be referenced as a good installation resource by the official documentation, should offer a public, direct support contact to those responsible for it, so that users can report issues and feel that there is ownership. Sadly, that's not the case in this very issue.

The following illustrates the issue that misleaded users trying those resources are facing:

Attempting to install a binary package for Ubuntu 20.04 will result in this:

```
$ sudo dpkg -i darktable_3.2.1-1.1_amd64.deb
Selecting previously unselected package darktable.
(Reading database ... 466817 files and directories currently installed.)
Preparing to unpack darktable_3.2.1-1.1_amd64.deb ...
Unpacking darktable (3.2.1-1.1) ...
dpkg: dependency problems prevent configuration of darktable:
 darktable depends on libexiv2-27 (>= 0.27.3); however:
  Version of libexiv2-27:amd64 on system is 0.27.2-8ubuntu2.
 darktable depends on libilmbase25 (>= 2.5.3); however:
  Package libilmbase25 is not installed.
 darktable depends on libjson-glib-1.0-0 (>= 1.5.2); however:
  Version of libjson-glib-1.0-0:amd64 on system is 1.4.4-2ubuntu2.
 darktable depends on libopenexr25 (>= 2.5.3); however:
  Package libopenexr25 is not installed.
```

And attempting to use the aforementioned PPA for the same distribution will generate this kind of errors:

```The following packages have unmet dependencies:
 darktable : Depends: libexiv2-27 (>= 0.27.3) but 0.27.2-8ubuntu2 is to be installed
             Depends: libilmbase25 (>= 2.5.3) but it is not installable
             Depends: libjson-glib-1.0-0 (>= 1.5.2) but 1.4.4-2ubuntu2 is to be installed
             Depends: libopenexr25 (>= 2.5.3) but it is not installable
E: Unable to correct problems, you have held broken packages.```

**Comment by paperdigits** [comment]
> One possible alternative could be modifying the wording of the page to make it (currently it is not) very explicit that DT.org does not maintain, test or endorse any claims made by any third party resources listed in the page.

That is what "3rd party" means precisely -- provided by someone else.

If the OBS latest release repo isn't working by 3.4 release time, I'll remove it, but keep in mind that "master" is the master branch and is prone to breaking.
