### ISSUE TITLE
Anchor pictures?

### ISSUE THREAD

**Issue by peterbud** [darktable-org/dtorg#13]
I get these paragraph marks for anchor picture. Is this intentional?
![image](https://user-images.githubusercontent.com/7863452/34576602-b3b44f08-f17e-11e7-96ca-ab7ee221185b.png)

**Comment by patdavid** [comment]
You should only be seeing those on hover I think.  Can you refresh hard and try again?

**Comment by peterbud** [comment]
OK, after F5 I see those only on hover. 

But is this really the picture we want to show? I recall @LebedevRI was using this is as a reference:
![image](https://user-images.githubusercontent.com/7863452/34578939-298845a6-f187-11e7-854c-51b1be12ac8f.png)

**Comment by patdavid** [comment]
I can make a new SVG to use as a link icon if we want.  This is similar to how github does it on markdown files right now.  I'll look into it early next week.

**Comment by LebedevRI** [comment]
What is the issue here, specifically?
The specific icon (i don't care, as long as it is there at all),
or the fact that sometimes they are all displayed (which is more visible, but also more noisy) (i think this is a bug).

**Comment by patdavid** [comment]
He said that a refresh fixed them from showing everywhere. I assume he means the specific icon is the issue.

**Comment by peterbud** [comment]
After hard refresh (F5) the anchor icons are shown only when the mouse hovers over the heading. So that is fixed apparently.
My second question was about the paragraph mark SVG itself. I have found it odd. My first feeling was "oops, looks like I'm editing a Word document?" 

@patdavid , as I see github is using these little link icons in MD files, eg [here](https://github.com/darktable-org/darktable/blob/master/README.md)

**Comment by houz** [comment]
I used the pilcrow as it's available in our standard font and used for this quite often all over the internet. I don't like using an embedded SVG as Github does. An alternative would be to use another font (Font Awesome comes to mind) or look through Open Sans for something else.

**Comment by peterbud** [comment]
It's not so important, lets leave the pilcrow. The main thing is that now those are appearing **only** on hover.
