### ISSUE TITLE
The OS selection screen can be difficult to understand

### ISSUE THREAD

**Issue by expipiplus1** [darktable-org/dtorg#135]
I observed someone come to the conclusion that darktable wasn't available on MacOS because they didn't recognize the MacOS option here: https://www.darktable.org/install/ (Is it using the Leopard logo?)

I think these would be greatly improved with using text alongside or instead of the logos, and perhaps grouping the many Unicies separately.

Some good examples:

https://transmissionbt.com/download/
https://code.visualstudio.com/download
https://signal.org/en/download/

**Comment by paperdigits** [comment]
Yes I agree. This is one of the pages that needs to be reworked. We are in the middle of porting the site to Hugo, so we'll address this after the port is finished.

Thanks!

**Comment by paperdigits** [comment]
@expipiplus1 I've updated the install page. Not as excellent as it could be, but I hope it is way clearer. If it is satisfactory, please close this issue.

**Comment by expipiplus1** [comment]
Thanks!
