### ISSUE TITLE
Instructions to submit patches are semi-obsolete?

### ISSUE THREAD

**Issue by moy** [darktable-org/dtorg#15]
At the bottom of http://www.darktable.org/development/, the instructions to contribute insist a lot on using `git format-patch origin/master`, but barely mention pull-requests. If I understand correctly, GitHub pull-requests are the preferred way to contribute (but I may well have missed something). The text should probably:

* Emphasis the pull-request based workflow
* Mention `git format-patch` but state more clearly that it is an alternative for people who don't want to use GitHub
* Link to https://github.com/darktable-org/darktable/blob/master/CONTRIBUTING.md

**Comment by patdavid** [comment]
I'm not sure what the preferred answer for this would be.  I'm fine with fixing the text if needed.

**Comment by houz** [comment]
True, those should be reworded.

**Comment by patdavid** [comment]
Should there be a section that focuses on a workflow around using GitHub specifically (forking, modifying, PR)?
I assume you'd want this separate from generic git instructions (in case of a repo change later?)?

**Comment by paperdigits** [comment]
Those instructions are no longer present on the page, closing.
