### ISSUE TITLE
3.6 blog article

### ISSUE THREAD

**Issue by kofa73** [darktable-org/dtorg#153]
**color balance rgb**
> Finally, the linear color-grading takes place in a specific RGB color space (published in 2019) to exhibit a uniform repartition of Munsell hues across the luminance range. 

- Any reason why the name of the RGB space is not provided?
- Perhaps 'special purpose' should be used instead of 'specific' (= 'clearly defined or identified'). sRGB is also a specific space.

(Cannot send a PR, as I don't know what space is used.)

**Color calibration**
> darktable 3.6 also introduces an OpenCL kernel for color calibration, which should be 0.3× to 8× faster than the CPU path, depending on hardware.

This is hard to interpret. If the speed is 0.3x that of the CPU path, it means it's slower. If the time taken is 30% less, then the 8x figure is meaningless ('the time taken is 800% less').

**Crop, Shapes, Retouch and Pipe Distortions**
> In addition, the gradient mask can now have its curvature set before it is placed on the image, and with greater accuracy.'

Maybe it's just me, but this sentence reads weird. Does this mean that the curvature of the mask can now be set more accurately?

**RCD**
> This method is also orders of magnitude faster than AMaZE

Is it really over 100x (2 orders of magnitude) as fast? If it's just a figure of speech, wouldn't _an order of magnitude_ be a better choice? Or simply _a lot faster than_, _several times as fast as_?

**Reverse blend modes**
> The darktable default for blending modes is to apply the module output over the module input with some optional transparency (using classical alpha compositing and assuming a fully opaque input). The reversed modes instead apply the input over the output.

It think it'd be worth mentioning that this is only important when drawn or parametric masks are involved (see https://discuss.pixls.us/t/find-a-creative-use-case-for-each-blend-mode/25089/3). But maybe that belongs to the manual?

**Comment by elstoc** [comment]
> Perhaps 'special purpose' should be used instead of 'specific'

Agree. I think that sounds better.

> Does this mean that the curvature of the mask can now be set more accurately?

Yes. Smaller steps for more precise curvature.

I'll leave @aurelienpierre to comment on the rest as it's mostly his text iirc.

**Comment by aurelienpierre** [comment]
> Any reason why the name of the RGB space is not provided?

It's not named. The paper in which is published is called something like "RGB space for even spacing of Munsell hues".

> This is hard to interpret. If the speed is 0.3x that of the CPU path, it means it's slower. If the time taken is 30% less, then the 8x figure is meaningless ('the time taken is 800% less').

Guess it should be 1.3× faster then.
