### ISSUE TITLE
Search broken: needs www prefix to work

### ISSUE THREAD

**Issue by kofa73** [darktable-org/dtorg#154]
Search works only if the 'www' prefix is used.
- https://darktable.org/usermanual/3.6/en/ - search does not work
- https://www.darktable.org/usermanual/3.6/en/ - search works fine

**Comment by elstoc** [comment]
We are aware of this (useful to have an issue raised though). There are similar problems if you use http.

Note that this is just an issue for the user manual - I think there are working redirects in place for the rest of darktable.org.

**Comment by elstoc** [comment]
This is fixed for the new url docs.darktable.org/usermanual/3.6/
