### ISSUE TITLE
The Features page contains some broken links

### ISSUE THREAD

**Issue by wubwubwubwubwubwubwubwub** [darktable-org/dtorg#162]
The Features page has some broken links to blogs, I think these are the correct links:

Ulrich's post (shadows and highlights):  https://www.darktable.org/2012/02/shadow-recovery-revisited/
Ulrich's post (tone curve): https://www.darktable.org/2012/02/mastering-color-with-lab-tone-curves/
Johannes' post (color correction): https://www.darktable.org/2012/03/color-correction/
Henrik's post (vibrance):  https://www.darktable.org/2011/10/different-kind-of-saturation/
"this post" (color LUT): https://www.darktable.org/2016/05/colour-manipulation-with-the-colour-checker-lut-module/
liquify post:  https://www.darktable.org/2016/04/liquify-liquify/
perspective correction:  https://www.darktable.org/2016/03/a-new-module-for-automatic-perspective-correction/
profiled denoise:  https://www.darktable.org/2012/12/profiling-sensor-and-photon-noise/
Ulrich's post (lowpass):  https://www.darktable.org/2012/02/using-lowpass-filter-to-recover-shadows/

**Comment by paperdigits** [comment]
Thanks! Can you submit a PR to fix it please?

**Comment by wubwubwubwubwubwubwubwub** [comment]
I believe I have made a pull request that fixes the links.  Sorry about the delay.

**Comment by paperdigits** [comment]
Fixed by e21cfeb94acec63210806e8f8e7887fbcdf20591
