### ISSUE TITLE
https://www.darktable.org/2021/07/darktable-3-6/ user manual, lua-doc links 404

### ISSUE THREAD

**Issue by roman-neuhauser** [darktable-org/dtorg#167]
At least two dead links in https://www.darktable.org/2021/07/darktable-3-6/ aka https://github.com/darktable-org/dtorg/blob/master/content/blog/2021-07-03-darktable-3.6/index.md:

> Thanks to countless hours of work of very dedicated contributors, all of the new features are fully documented in time in the [user manual](https://docs.darktable.org/usermanual/3.6/en)

https://docs.darktable.org/usermanual/3.6/en/ works.  

> This time we are also launching a new version of the lua documentation, [here](https://www.darktable.org/lua-docs/3.6/).

No idea what the correct URL is here.

**Comment by elstoc** [comment]
We have some work to do on the url redirects. It's in progress.

**Comment by Nilvus** [comment]
This is no more a 404. @roman-neuhauser: could you please close this issue?

**Comment by elstoc** [comment]
There is still a 404 on the link to the lua docs but I'm not sure if we're going to fix this.

**Comment by paperdigits** [comment]
We're not going to fix it, and 3.6 is so old that not even any current distro has it :D
