### ISSUE TITLE
https://www.darktable.org/resources/ link to the HTML Lua API docs is 404

### ISSUE THREAD

**Issue by roman-neuhauser** [darktable-org/dtorg#168]
see title.

**Comment by elstoc** [comment]
Same again. This is WIP.

**Comment by roman-neuhauser** [comment]
How much more "W" do you expect this to be?

**Comment by elstoc** [comment]
It'll be done when it's done.

**Comment by Nilvus** [comment]
This is no more a 404. @roman-neuhauser: could you please close this issue?
