### ISSUE TITLE
New grey screenshot on home page for darktable 4.0 release?

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/dtorg#187]
As darktable 4.0 will be with now grey theme by default, maybe screenshot on darktable.org homepage will need to be updated for the darktable 4.0 release day?
Actual screenshot is mine (with some of my photos).

@elstoc: as this move is thanks to you, I think it would be good if that time screenshot is from your side. If you want of course.

**Comment by ralfbrown** [comment]
How about this?  Run in a new config directory, so all settings at default except I increased font size for readability at smaller sizes.  Thumbnails are all images I've taken, so I can license this screenshot CC-whatever.

![darktable50lighttable](https://github.com/user-attachments/assets/f72a5ec6-e9ea-49f2-98e5-a4cc0e01afa0)

**Comment by elstoc** [comment]
There was a thread on pixls where loads of people donated their own images for this sort of thing. Might get more variety with those

**Comment by ralfbrown** [comment]
After much searching, I think I found the thread you were thinking of: https://discuss.pixls.us/t/submit-your-sample-images-for-upcoming-darktable-content/44567.  New screenshot below.

Image credits for thumbnails:
|  |  |  |  |  |
|---|---|---|---|---|
| 01McAc | 123sg | 123sg | CPfister | ralfbrown |
| ralfbrown | ralfbrown | ralfbrown | ralfborwn | ralfbrown |
| ralfbrown | ralfbrown | ralfbrown | clind | clind |
| kap55 | luator | nish | nish | sugarbravo |

![darktable50lighttable](https://github.com/user-attachments/assets/cbf30c0a-5df7-45ea-bc91-0b741c5659eb)

**Comment by elstoc** [comment]
> Image credits for thumbnails

I believe most of these are CC BY-NC. I'm not sure the best way to give attribution. Maybe in the commit that submits the image?

**Comment by ralfbrown** [comment]
Correct.  I skipped images in that thread where the poster didn't explicitly state a license.  I've also now found another thread:
https://discuss.pixls.us/t/darktable-4-2-is-coming-simply-thank-you/34203

PR coming momentarily.  I put the below matrix  in the commit message and a simple list in the image title text which pops up on hover.

Updated credits:
| | | | | |
|---|---|---|---|---|
| 01McAc | 123sg | 123sg | CPfister | ralfbrown |
| ralfbrown | ralfbrown | ralfbrown | ralfbrown | ralfbrown |
| clind | clind | jdneumeyer | kap55 | luator |
| nish | qmpel | quovadit | rudantu | sugarbravo |
