### ISSUE TITLE
Turn the camera support list into a positive list and improve reading

### ISSUE THREAD

**Issue by illwieckz** [darktable-org/dtorg#195]
The camera support list [here](https://www.darktable.org/resources/camera-support/) ans [here](https://github.com/darktable-org/dtorg/blob/master/content/resources/camera-support.md),

- focuses on what's not supported (“No” is bold and capitalized instead of “Yes”),
- may not be easy to read as
  * when looking globally it may not be easy for the eye to quickly catch the obvious when Yes and No look a lot similar,
  * when looking precisely the boldness and the capitalization of “No” may drift the eye outside of the “line of Yes”.

The first point is opinionated though, but it may be more useful or convenient for the user to focus on what's supported, and better for the darktable project communication to focus on achievements.

Without turning the list into a christmas tree like [this](https://wiki.unvanquished.net/wiki/GPU_compatibility_matrix) (I'm the one who did this one), it may be possible to produce something better. I have not found the generator of the table but I see you already use an html table so it may be possible to do more catchy styling. Even without coloring the text or the cell background, one can simply add a coloured emoji (a bit like this [other one](https://wiki.unvanquished.net/wiki/Tools/Level_editors#Level_editors) I did, though I would recommend keeping the “Yes“ and “No” word as you have the space for them).

Here is a very simple example done by just swapping the boldness and capitalization from “No” to “Yes”, and adding a green checkmark next to Yes.

I chose the ✔️ emoji here in this issue because it is drawn as green in GitHub (but usually [black without background](https://emojipedia.org/check-mark/), GitHub does weird stuff with emojis), but you may prefers others like ✅ (usually [white on green](https://emojipedia.org/check-mark-button/) but GitHub…) or ☑️ (usually [white on blue](https://emojipedia.org/check-box-with-check/) but GitHub…), or simply a green square 🟩. You would select the best one according to the font used on `darktable.org`.

<table class="smalltext altrows u-full-width">
  <thead><tr>
    <th><strong>Camera</strong><br/>699 (100%)</th>
    <th><strong>WB Presets</strong><br/>453 (64%)</th>
    <th><strong>Noise Profile</strong><br/>373 (53%)</th>
    <th><strong>Custom Matrix</strong><br/>116 (16%)</th>
  </tr></thead>
  <tr><td>Canon EOS 1000D</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td></tr>
  <tr><td>Canon EOS Digital Rebel XS</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td></tr>
  <tr><td>Canon EOS Kiss Digital F</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td></tr>
  <tr><td>Canon EOS 100D</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td></tr>
  <tr><td>Canon EOS Kiss X7</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td></tr>
  <tr><td>Canon EOS Rebel SL1</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td></tr>
  <tr><td>Canon EOS 10D</td><td><strong>✔️ YES</strong></td><td>No</td><td>No</td></tr>
  <tr><td>Canon EOS 1100D</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td>No</td></tr>
  <tr><td>Canon EOS Rebel T3</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td>No</td></tr>
  <tr><td>Canon EOS 1200D</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td>No</td></tr>
  <tr><td>Canon EOS Kiss X70</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td>No</td></tr>
  <tr><td>Canon EOS Rebel T5</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td>No</td></tr>
  <tr><td>Canon EOS 1300D</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td>No</td></tr>
  <tr><td>Canon EOS Kiss X80</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td>No</td></tr>
  <tr><td>Canon EOS Rebel T6</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td>No</td></tr>
  <tr><td>Canon EOS 1500D</td><td>No</td><td>No</td><td>No</td></tr>
  <tr><td>Canon EOS 2000D</td><td>No</td><td>No</td><td>No</td></tr>
  <tr><td>Canon EOS Rebel T7</td><td>No</td><td>No</td><td>No</td></tr>
  <tr><td>Canon EOS 200D</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td>No</td></tr>
  <tr><td>Canon EOS Kiss X9</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td>No</td></tr>
  <tr><td>Canon EOS Rebel SL2</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td>No</td></tr>
  <tr><td>Canon EOS 20D</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td></tr>
  <tr><td>Canon EOS 300D</td><td><strong>✔️ YES</strong></td><td>No</td><td>No</td></tr>
  <tr><td>Canon EOS Digital Rebel</td><td><strong>✔️ YES</strong></td><td>No</td><td>No</td></tr>
  <tr><td>Canon EOS Kiss Digital</td><td><strong>✔️ YES</strong></td><td>No</td><td>No</td></tr>
  <tr><td>Canon EOS 30D</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td></tr>
  <tr><td>Canon Digital Rebel XT</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td></tr>
  <tr><td>Canon EOS 350D</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td></tr>
  <tr><td>Canon Kiss Digital N</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td></tr>
  <tr><td>Sony ZV-1</td><td>No</td><td>No</td><td>No</td></tr>
</table>

You may even add next to the camera name a symbol that quickly summarizes the support completeness for a camera so the other columns only have to be read when it's either not fully supported or not supported at all.

<table class="smalltext altrows u-full-width">
  <thead><tr>
    <th><strong>Camera</strong><br/>699 (100%)</th>
    <th><strong>WB Presets</strong><br/>453 (64%)</th>
    <th><strong>Noise Profile</strong><br/>373 (53%)</th>
    <th><strong>Custom Matrix</strong><br/>116 (16%)</th>
  </tr></thead>
  <tr><td>🟩 Canon EOS 1000D</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td></tr>
  <tr><td>🟩 Canon EOS Digital Rebel XS</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td></tr>
  <tr><td>🟩 Canon EOS Kiss Digital F</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td></tr>
  <tr><td>🟩 Canon EOS 100D</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td></tr>
  <tr><td>🟩 Canon EOS Kiss X7</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td></tr>
  <tr><td>🟩 Canon EOS Rebel SL1</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td></tr>
  <tr><td>🟧 Canon EOS 10D</td><td><strong>✔️ YES</strong></td><td>No</td><td>No</td></tr>
  <tr><td>🟩 Canon EOS 1100D</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td>No</td></tr>
  <tr><td>🟩 Canon EOS Rebel T3</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td>No</td></tr>
  <tr><td>🟩 Canon EOS 1200D</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td>No</td></tr>
  <tr><td>🟩 Canon EOS Kiss X70</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td>No</td></tr>
  <tr><td>🟩 Canon EOS Rebel T5</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td>No</td></tr>
  <tr><td>🟩 EOS 1300D</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td>No</td></tr>
  <tr><td>🟩 Canon EOS Kiss X80</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td>No</td></tr>
  <tr><td>🟩 Canon EOS Rebel T6</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td>No</td></tr>
  <tr><td>⬛ Canon EOS 1500D</td><td>No</td><td>No</td><td>No</td></tr>
  <tr><td>⬛ Canon EOS 2000D</td><td>No</td><td>No</td><td>No</td></tr>
  <tr><td>⬛ Canon EOS Rebel T7</td><td>No</td><td>No</td><td>No</td></tr>
  <tr><td>🟧 Canon EOS 200D</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td>No</td></tr>
  <tr><td>🟧 Canon EOS Kiss X9</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td>No</td></tr>
  <tr><td>🟧 Canon EOS Rebel SL2</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td>No</td></tr>
  <tr><td>🟩 Canon EOS 20D</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td></tr>
  <tr><td>🟧 Canon EOS 300D</td><td><strong>✔️ YES</strong></td><td>No</td><td>No</td></tr>
  <tr><td>🟧 Canon EOS Digital Rebel</td><td><strong>✔️ YES</strong></td><td>No</td><td>No</td></tr>
  <tr><td>🟧 Canon EOS Kiss Digital</td><td><strong>✔️ YES</strong></td><td>No</td><td>No</td></tr>
  <tr><td>🟩 Canon EOS 30D</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td></tr>
  <tr><td>🟩 Canon Digital Rebel XT</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td></tr>
  <tr><td>🟩 Canon EOS 350D</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td></tr>
  <tr><td>🟩 Canon Kiss Digital N</td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td><td><strong>✔️ YES</strong></td></tr>
  <tr><td>⬛ Sony ZV-1</td><td>No</td><td>No</td><td>No</td></tr>
</table>

_Note:_ instead of ⬛ you can use 🟥 but it may break the “focus on what is supported“ principle, there are other options: ◻🔲◻️, etc.

_Edit:_ As the first column “may be enough”, readibility may be better this way by not catching the eye with what is only needed to be read when it's not fully on or off:

<table class="smalltext altrows u-full-width">
  <thead><tr>
    <th><strong>Camera</strong><br/>699 (100%)</th>
    <th><strong>WB Presets</strong><br/>453 (64%)</th>
    <th><strong>Noise Profile</strong><br/>373 (53%)</th>
    <th><strong>Custom Matrix</strong><br/>116 (16%)</th>
  </tr></thead>
  <tr><td>🟩 Canon EOS 1000D</td><td><strong>YES</strong></td><td><strong>YES</strong></td><td><strong>YES</strong></td></tr>
  <tr><td>🟩 Canon EOS Digital Rebel XS</td><td><strong>YES</strong></td><td><strong>YES</strong></td><td><strong>YES</strong></td></tr>
  <tr><td>🟩 Canon EOS Kiss Digital F</td><td><strong>YES</strong></td><td><strong>YES</strong></td><td><strong>YES</strong></td></tr>
  <tr><td>🟩 Canon EOS 100D</td><td><strong>YES</strong></td><td><strong>YES</strong></td><td><strong>YES</strong></td></tr>
  <tr><td>🟩 Canon EOS Kiss X7</td><td><strong>YES</strong></td><td><strong>YES</strong></td><td><strong>YES</strong></td></tr>
  <tr><td>🟩 Canon EOS Rebel SL1</td><td><strong>YES</strong></td><td><strong>YES</strong></td><td><strong>YES</strong></td></tr>
  <tr><td>🟧 Canon EOS 10D</td><td><strong>YES</strong></td><td>No</td><td>No</td></tr>
  <tr><td>🟩 Canon EOS 1100D</td><td><strong>YES</strong></td><td><strong>YES</strong></td><td>No</td></tr>
  <tr><td>🟩 Canon EOS Rebel T3</td><td><strong>YES</strong></td><td><strong>YES</strong></td><td>No</td></tr>
  <tr><td>🟩 Canon EOS 1200D</td><td><strong>YES</strong></td><td><strong>YES</strong></td><td>No</td></tr>
  <tr><td>🟩 Canon EOS Kiss X70</td><td><strong>YES</strong></td><td><strong>YES</strong></td><td>No</td></tr>
  <tr><td>🟩 Canon EOS Rebel T5</td><td><strong>YES</strong></td><td><strong>YES</strong></td><td>No</td></tr>
  <tr><td>🟩 EOS 1300D</td><td><strong>YES</strong></td><td><strong>YES</strong></td><td>No</td></tr>
  <tr><td>🟩 Canon EOS Kiss X80</td><td><strong>YES</strong></td><td><strong>YES</strong></td><td>No</td></tr>
  <tr><td>🟩 Canon EOS Rebel T6</td><td><strong>YES</strong></td><td><strong>YES</strong></td><td>No</td></tr>
  <tr><td>⬛ Canon EOS 1500D</td><td>No</td><td>No</td><td>No</td></tr>
  <tr><td>⬛ Canon EOS 2000D</td><td>No</td><td>No</td><td>No</td></tr>
  <tr><td>⬛ Canon EOS Rebel T7</td><td>No</td><td>No</td><td>No</td></tr>
  <tr><td>🟧 Canon EOS 200D</td><td><strong>YES</strong></td><td><strong>YES</strong></td><td>No</td></tr>
  <tr><td>🟧 Canon EOS Kiss X9</td><td><strong>YES</strong></td><td><strong>YES</strong></td><td>No</td></tr>
  <tr><td>🟧 Canon EOS Rebel SL2</td><td><strong>YES</strong></td><td><strong>YES</strong></td><td>No</td></tr>
  <tr><td>🟩 Canon EOS 20D</td><td><strong>YES</strong></td><td><strong>YES</strong></td><td><strong>YES</strong></td></tr>
  <tr><td>🟧 Canon EOS 300D</td><td><strong>YES</strong></td><td>No</td><td>No</td></tr>
  <tr><td>🟧 Canon EOS Digital Rebel</td><td><strong>YES</strong></td><td>No</td><td>No</td></tr>
  <tr><td>🟧 Canon EOS Kiss Digital</td><td><strong>YES</strong></td><td>No</td><td>No</td></tr>
  <tr><td>🟩 Canon EOS 30D</td><td><strong>YES</strong></td><td><strong>YES</strong></td><td><strong>YES</strong></td></tr>
  <tr><td>🟩 Canon Digital Rebel XT</td><td><strong>YES</strong></td><td><strong>YES</strong></td><td><strong>YES</strong></td></tr>
  <tr><td>🟩 Canon EOS 350D</td><td><strong>YES</strong></td><td><strong>YES</strong></td><td><strong>YES</strong></td></tr>
  <tr><td>🟩 Canon Kiss Digital N</td><td><strong>YES</strong></td><td><strong>YES</strong></td><td><strong>YES</strong></td></tr>
  <tr><td>⬛ Sony ZV-1</td><td>No</td><td>No</td><td>No</td></tr>
</table>

**Comment by paperdigits** [comment]
This is more or less done. Thanks!
