### ISSUE TITLE
Please add Chromebook installation instructions to the main installation page on the website (I wrote some)

### ISSUE THREAD

**Issue by mrjohnc** [darktable-org/dtorg#204]
I use Darktable on my Chromebook (works well) but I realised that [the main installation page on the website](https://www.darktable.org/install/) doesn't even tell people it works on Chromebooks. I think having instructions for Chromebook would be really helpful given the number of Chromebooks there are.

I've written some basic instructions which should give people all the information they need, but I'm sure could be refined.

Step 1: Enable Linux support on your Chromebook by following [these instructions](https://support.google.com/chromebook/answer/9145439?hl=en), not all older Chromebooks are compatible.

Step 2: Once you have done this you can install through the [Linux Terminal](https://chromeos.dev/en/productivity/terminal) either through:

Option 1: use these commands to install and uninstall Darktable

Install: sudo apt install darktable
Uninstall: sudo apt remove darktable && sudo apt autoremove

Option 2: Install through Flatpak

Install FlatPak using [these instructions](https://www.flatpak.org/setup/Chrome%20OS)
Install Darktable using the command line instruction on [this page](https://flathub.org/apps/details/org.darktable.Darktable)

**Comment by paperdigits** [comment]
I don't think the chromebook is a great platform for darktable. Most of them will provide a supremely subpar experience.
