### ISSUE TITLE
Add caveat for unsupported camera compression modes

### ISSUE THREAD

**Issue by kmilos** [darktable-org/dtorg#208]
Just like the 4.2 release notes, the https://www.darktable.org/resources/camera-support/ page should also clearly state (before the table preferably) that these compression modes are not currently supported:

* Fujifilm lossy
* Nikon high efficiency
* Sony lossless

This should help set expectations and reduce constant opening of related duplicate issues.

**Comment by paperdigits** [comment]
Added in https://github.com/darktable-org/dtorg/commit/6a1708a2a30633b71c970a5727059f9168e0c839
