### ISSUE TITLE
Resources: illogical links

### ISSUE THREAD

**Issue by LebedevRI** [darktable-org/dtorg#22]
https://www.darktable.org/resources/
```
You can either read the manual online or download it in PDF format:
* English
* French
* Italian
* Spanish
```
Every single time i press on english, and it opens pdf download.
something like this would be less hostile.
```
You can either read the manual online:
* English
or download it in PDF format:
* English
* French
* Italian
* Spanish
```

**Comment by patdavid** [comment]
What about adding "(en)" after the online link?

so: ` ...read the manual online (en) or download it in...`

**Comment by LebedevRI** [comment]
I don't notice that inline link there, adding 5 chars won't really solve it.
This is why i suggested making it a whole new list of [currently] one item.
