### ISSUE TITLE
SSL Cert expired

### ISSUE THREAD

**Issue by jerrac** [darktable-org/dtorg#23]
FYI, Firefox is telling that the SSL certificate for darktable.org is expired. Same story for redmine.darktable.org.

> www.darktable.org uses an invalid security certificate. 
> The certificate expired on August 19, 2018, 12:01:50 AM GMT-7. The current time is August 19, 2018, 12:51 PM. 
> Error code: SEC_ERROR_EXPIRED_CERTIFICATE

Same story using a private window or Chromium (never visited darktable.org via Chromium before.)

**Comment by patdavid** [comment]
Closing, as this was resolved.
