### ISSUE TITLE
DT4.4 Documentation issue (RE Settings > Processing > auto-apply chromatic adaptation defaults)

### ISSUE THREAD

**Issue by arigit** [darktable-org/dtorg#231]
The option: "auto-apply chromatic adaptation defaults" is referred to in the current documentation here: 

https://darktable-org.github.io/dtdocs/en/preferences-settings/processing/

However that option is missing in DT4.4 and DT4.4.1

The omission is by design, as discussed here, https://github.com/darktable-org/darktable/issues/12917, so the issue is that the documentation has not been updated to reflect this.

Also, consistent with https://github.com/darktable-org/darktable/issues/12917, I am using a scene-referred workflow and I noticed the color-calibration module got auto-enabled.

**Comment by paperdigits** [comment]
I see your PR in the dtdocs repo and will address it there. Thanks!
