### ISSUE TITLE
Website offline

### ISSUE THREAD

**Issue by miiichael** [darktable-org/dtorg#234]
Connection refused!
![image](https://github.com/darktable-org/dtorg/assets/4179353/f3c890fa-7a79-4409-9664-a3a84013d42e)

**Comment by patdavid** [comment]
Yes, we had hardware issues on the server. We are spooling up a new server now and hopefully will be back online asap.

**Comment by erickpaquin** [comment]
How about getting some mirroring happening or some kind of HA?

**Comment by Gared** [comment]
Is there a way to help you? Maybe we can use Github Pages?

**Comment by paperdigits** [comment]
All we are waiting on is someone to point the DNS to our new server.

**Comment by heitorPB** [comment]
Website is up again!

**Comment by paperdigits** [comment]
Yes, let's close this issue please.
