### ISSUE TITLE
Canon 90D is supported, however isn't mentioned on the camera supported list.

### ISSUE THREAD

**Issue by ricardojfc** [darktable-org/dtorg#246]
Hi,

Canon EOS 90D is supported version 3.8.x according to [PR#10897](https://github.com/darktable-org/darktable/pull/10897). including the `Noise profile`.

On the [PR#199](https://github.com/darktable-org/dtorg/pull/199/files#diff-ea06c4ed7691dbd16ea447483684897814704a213f8059aa3d16cd685a3820c4R129) It is mentioned but isn't on the `master` branch.

Please include it with this line:
```
 <tr><td>Canon EOS 90D</td><td><strong>NO</strong></td><td><strong>Yes</strong></td><td><strong>NO</strong></td></tr>
```

I'm currently own an EOS 90D and works perfectly with darktable version 4.2.1

**Comment by paperdigits** [comment]
Hi, thanks for the issue.

We are looking for a way to auto generate this table from the source code, since nobody wants to maintain it by hand. We are open to ideas on how to accomplish that!

**Comment by paperdigits** [comment]
A tool has be written and I've updated the table on https://github.com/darktable-org/dtorg/commit/10b2de8d38710a977358ed2c89cbc1ef71109044
