### ISSUE TITLE
Adding Docs for high quality processing

### ISSUE THREAD

**Issue by jenshannoschwalm** [darktable-org/dtorg#252]
For some reason i can't open a pr (as i usually do for darktable. So here we go ...

1. In `content/darkroom/darkroom-view-layout.md` i suggest to add after the focus-peak stuff
```
![high-quality-processing-icon](./darkroom-view-layout/high-quality-processing-icon.png#icon) [high quality processing](../module-reference/utility-modules/darkroom/high-quality-processing.md)
: Toggle high quality processing mode.
```

2. The icon could be 
![high-quality-processing-icon](https://github.com/user-attachments/assets/d8bce8fe-57cf-40de-8750-d80beaa4d26d)

3. The description could be like

[high-quality-processing.md](https://github.com/user-attachments/files/16431750/high-quality-processing.md)

**Comment by elstoc** [comment]
> For some reason i can't open a pr

weird, we have had PRs from noobs recently so no idea what could be causing that

**Comment by elstoc** [comment]
This will also need a replacement screenshot for https://docs.darktable.org/usermanual/4.6/en/darkroom/darkroom-view-layout/ as well please. Note that I hacked around with DPI and stuff in darktable to make that image more readable, and it would be good to get another with similar dimensions

**Comment by paperdigits** [comment]
Is this supposed to be on dtdocs?

**Comment by jenshannoschwalm** [comment]
> Is this supposed to be on dtdocs?

Yes :-)

**Comment by paperdigits** [comment]
If you made the change in the dtdocs repo and tried to open a PR against this repo, it'd make sense that it didn't work @jenshannoschwalm :dagger: 

This is for the website, dtorg.

**Comment by jenshannoschwalm** [comment]
Arrrg! Thanks for hinting...

**Comment by paperdigits** [comment]
I can make this a PR on the dtdocs repo if you'd like.

**Comment by elstoc** [comment]
lol I didn't even notice this was on the dtorg repo

**Comment by jenshannoschwalm** [comment]
> I can make this a PR on the dtdocs repo if you'd like.

I would love that !

**Comment by paperdigits** [comment]
Closing, I opened a PR at https://github.com/darktable-org/dtdocs/pull/675

Thanks @jenshannoschwalm
