### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by lcl4o** [darktable-org/dtorg#256]
I don't see a contributing section here. How can I help and how would you like help with the website? I can offer a lot of time, frontend and UX/UI skills.

**Comment by paperdigits** [comment]
hey, thanks for reaching out. A designer has been working on a new design which I really like, but it isn't ready to go yet, so we've been in a holding pattern on rolling out a new design. 

Do you have any suggestions?

**Comment by lcl4o** [comment]
thanks for the fast answer! I'm looking forward for the new design. I coded some basic improvements for the install page to learn how it is built. I can create a PR if you want.

![Screenshot from 2024-10-26 06-46-58](https://github.com/user-attachments/assets/58675c91-cdb0-46b1-a7c7-568a1a3eee88)

Other suggestions would be improving the typography a bit and the sizing and spacing from headings, code clocks and text. Maybe a darker blue or other color from the logo for the links, since the contrast is not so good. 

Is there anything else i can do for darktable? I also speak German. Is there translation work or could the docs be improved? Other frontend or UX work?

**Comment by paperdigits** [comment]
> Other suggestions would be improving the typography a bit and the sizing and spacing from headings, code clocks and text. Maybe a darker blue or other color from the logo for the links, since the contrast is not so good.

This sounds like a great place to start.

> I also speak German. Is there translation work or could the docs be improved?

Yes, but its down. You can use the PO file in the dtdocs repo if you want to get started.

**Comment by lcl4o** [comment]
i created a small PR. I close this issue now.
