### ISSUE TITLE
Update and rearrange 'resources' page on the website

### ISSUE THREAD

**Issue by pphotography** [darktable-org/dtorg#52]
After taking a look at the 'resources' page on the darktable website it came to my mind that an update should be done.

## Rearrangement ##
First of all this is a very long page containing different topics. Currently there are: 

- Frequently Asked Questions
- User manual
- Lua API documentation
- Darktable Styles
- Darktable book
- Screencast tutorials (newer versions)
- Screencast tutorials (older versions)
- Video tutorials in other languages
- Contributing backtraces
- List of supported cameras

To increase the website's lucidity I recommend splitting these topics into two pages, one with manuals/tutorials for learning the program usage and one with the remaining resources.

An idea is to call the new page 'learning' with the following content:

- User manual
- Darktable book
- Video tutorials in other languages
- Screencast tutorials (newer versions)
- Screencast tutorials (older versions)

This would lead to this remaining 'resources' page:

- Darktable Styles
- Frequently Asked Questions
- Lua API documentation
- Contributing backtraces
- List of supported cameras

## Content update ##
The 'learning' content could need an update. Some of the linked resources are not available anymore.
Moreover, there are many newer sites and video channels which are not listed on the page and should be included.

## My contribution offer ##
I could make an overview of the learning material, which is up-to-date, outdated or not available anymore.
Then I could provide a list of learning resources that could be added to the 'learning' page
Then I could provide two markdown files to contribute.

**Comment by patdavid** [comment]
I agree that clarifying this page and resources would certainly make sense.

**Comment by pphotography** [comment]
![resources_analysis](https://user-images.githubusercontent.com/49001045/55539424-e4921800-56c0-11e9-8486-79dcc1482c25.png)

I've checked the links on the resources page and their content.

- The most recent and complete learning resource is the Darktable manual.
- The book's content is mostely covered by the manual
- The videos' creation dates vary from 2011 to 2019 

Since there is no update on many outdated content and some of it is not available anymore this page looks like it's from an abandoned project which is not active anymore.

I know that some of the outdated content is usable in the newest Darktable version, but which beginner is able to separate relevant from irrelevant information?

The book's content is mostly covered by the Darktable manual. Updating and maintaining it would bring back two different documentations with almost the same content.

Therefore I recommend to remove all content older than for version 2.0.

**Comment by patdavid** [comment]
This seems sound to me.  I'd defer to @houz or @hanatos if they had any input, but keeping the information current and relevant is certainly important.

We could rearrange some things and add some text to add caveats for older (but possibly still relevant) videos/content.  Do the book authors (Stefano Fornari, Mario Latronico and Nicholas Manea) respond at all about possibly updating or maintaining it?  If not, I'd agree we should probably remove it from here.

**Comment by pphotography** [comment]
How can i contact the book authors? The book only contains their names and sourceforge.net only usernames.

**Comment by pphotography** [comment]
OK, here is the current state of my research:

----------

# User manual

You can read the manual (v2.6) online or download a PDF-version:

  * [**English online**](https://darktable.gitlab.io/doc/en/) / [Download PDF](https://github.com/darktable-org/darktable/releases/download/release-2.6.1/darktable-usermanual.pdf)
  * [**French online**](https://darktable.gitlab.io/doc/fr/) / [Download PDF](https://github.com/darktable-org/darktable/releases/download/release-2.6.1/darktable-usermanual-fr.pdf)
  * [**German online**](https://darktable.gitlab.io/doc/de/) / [Download PDF](https://github.com/darktable-org/darktable/releases/download/release-2.6.1/darktable-usermanual-de.pdf)
  * [**Italian online**](https://darktable.gitlab.io/doc/it/) / [Download PDF](https://github.com/darktable-org/darktable/releases/download/release-2.6.1/darktable-usermanual-it.pdf)

Translations into other languages are currently being worked on and will be published as soon as they are ready.

# Videos
On the internet you can find many video tutorials about learning Darktable and applying various techniques to your images, here is a selection:

## English
  * [Boris Hajdukovic](https://www.youtube.com/playlist?list=PLmZmCIhOC2Frt6Wq3gc0-egOy_P1sXjau)
  * [Bruce Williams photography](https://www.youtube.com/playlist?list=PLlYWvzmJQTrRq7JrYdD7k3-8-v-uHnhK_)
  * [Harry Durgin](https://www.youtube.com/playlist?list=PLsks-zRRM1ZVN_g7P6ZAsYVqTltmXyBjl)
  * [HPBirkeland Photography](https://www.youtube.com/channel/UCORg6wKMeM1RBFVGbUc9jgw/videos)
  * [Keifer Hunniford](https://www.youtube.com/channel/UCM8XE_Gv3Ui5s4F-5TW16jg/videos)
  * [Riley Brandt](https://www.youtube.com/playlist?list=PL33t7emXCBHkMfiP1IcO-0_4mUAhh1lFA)

## German
  * [Der Hobby Photograph](https://www.youtube.com/playlist?list=PLKz_RsdryfNp5M03AcBdNSyeVo_ycFCXi)
  * [MyGimpTutorialChannel](https://www.youtube.com/playlist?list=PLtO5kAK5wcRYio14-ECeo-C_wmmClKIrH)

## French
  * [Aurélien PIERRE Photo](https://www.youtube.com/playlist?list=PL4EYo8VotTsih9QXYM06x2SQRkuuiTAHx)
  * [Carafife](https://www.youtube.com/playlist?list=PLZOdZMT41b7W0IBntprxOOqlw54iiKRMb)
  * [Juste une mise au point](https://www.youtube.com/channel/UCSXBAkUFaqTZyWYW2BCa-FA/playlists)
  * [Philippe Delétrée](https://www.youtube.com/channel/UCyuC63yBPP5vteLZ-l7T8OA/videos)
  * [Rawfiner](https://www.youtube.com/channel/UCEz-0EYZTx03UdQszbL8xDA/videos)





# Archive
These resources were made for older Darktable versions, but most content is still valid.


## The book
![cover]({attach}cover.jpg)

Stefano Fornari, Mario Latronico and Nicholas Manea wrote a book about photo development with darktable:

**Digital photo development with darktable**
_Manage and develop your digital images with darktable._

It introduces you to the process of developing your images with darktable explaining the basic features. It starts over with a simple tutorial on importing and developing your first photo(s). After describing the darktable user interface it provides some workflow suggestions and background informations on (perception of light, sensors, patterns, colors).

You can download the [pdf](https://sourceforge.net/projects/darktable/files/darktable/book/1.1.1/darktable-1.1.1.pdf/download) or [packaged](https://sourceforge.net/projects/darktable/files/darktable/book/1.1.1/darktable-book-1.1.1.zip/download) version of the current release (v1.1.1). Your comments and feedback are always welcome on the [darktable user mailing list](mailto:darktable-user+subscribe@lists.darktable.org).


# Screencast tutorials
![vaxholmen]({attach}vaxholmen.jpg)

## Screencasts recorded using the latest development versions of darktable

There are many brilliant screencasts on darktable, its various modules and general image development workflow made by Robert Hutton. You can get the full playlist of these very educational screencasts here:

  * [Robert Hutton's darktable screencast playlist](https://www.youtube.com/playlist?list=PLmvlUro_Up1NBX7VK8UUuyWo1B468zEA0)
  * [Bruce Williams's darktable screencast playlist](https://www.youtube.com/playlist?list=PLlYWvzmJQTrRq7JrYdD7k3-8-v-uHnhK_)

Pascal de Bruijn provides several useful screencasts on his website explaining the different functions of dartkable. Find the [0.7 screencast library](https://encrypted.pcode.nl/blog/2010/12/06/darktable-0-7-screencast-library/), the [0.9 screencast library addition](https://encrypted.pcode.nl/blog/2011/11/05/darktable-0-9-screencast-library-addition/) and the [1.0 screencast library addition](https://encrypted.pcode.nl/blog/2012/06/02/darktable-1-0-screencast-library-addition/) or just pick the one you want:

## Screencasts recorded using darktable 1.0

  * [darktable 1.0 Update](https://encrypted.pcode.nl/blog/wp-content/uploads/2012/05/darktable-10-update.ogv)

  * [darktable Archiving & Backup](https://encrypted.pcode.nl/blog/wp-content/uploads/2012/05/darktable-10-archiving.ogv)

## Screencasts recorded using darktable 0.9

  * [darktable 0.9 Update](https://encrypted.pcode.nl/blog/wp-content/uploads/2011/10/22/darktable-update.ogv)
  * [darktable B&W Film Emulation](https://encrypted.pcode.nl/blog/wp-content/uploads/2011/10/22/darktable-bwfilmemu.ogv)
  * [darktable Denoising](https://encrypted.pcode.nl/blog/wp-content/uploads/2011/10/22/darktable-denoise.ogv)
  * [darktable Spot Removal](https://encrypted.pcode.nl/blog/wp-content/uploads/2011/10/22/darktable-spotremoval.ogv)

## Screencasts recorded using darktable 0.7 (but still valid)

  * [darktable Installation On Ubuntu](https://encrypted.pcode.nl/blog/wp-content/uploads/2010/12/darktable-ubuntu-installation.ogv)
  * [darktable Lighttable Basics](https://encrypted.pcode.nl/blog/wp-content/uploads/2010/12/darktable-lighttable-basics.ogv)
  * [darktable Tagging & Collect Modules](https://encrypted.pcode.nl/blog/wp-content/uploads/2010/12/darktable-lighttable-tagging-collect.ogv)
  * [darktable Darkroom Basics](https://encrypted.pcode.nl/blog/wp-content/uploads/2010/12/darktable-darkroom-basics.ogv)
  * [darktable Darkroom Black & White Modules](https://encrypted.pcode.nl/blog/wp-content/uploads/2010/12/darktable-darkroom-plugins-bw.ogv)
  * [darktable Darkroom GND Module](https://encrypted.pcode.nl/blog/wp-content/uploads/2010/12/darktable-darkroom-plugins-gnd.ogv)
  * [darktable Darkroom Colorzones Module](https://encrypted.pcode.nl/blog/wp-content/uploads/2010/12/darktable-darkroom-plugins-colorzones.ogv)
  * [darktable Darkroom Watermark Module](https://encrypted.pcode.nl/blog/wp-content/uploads/2010/12/darktable-darkroom-plugins-watermark.ogv)
  * [darktable Working With Styles](https://encrypted.pcode.nl/blog/wp-content/uploads/2010/12/darktable-styles.ogv)
  * [darktable Capture Basics](https://encrypted.pcode.nl/blog/wp-content/uploads/2010/12/darktable-capture-basics.ogv)

## Tutorial videos in Spanish (with subtitles in French and English)

(courtesy of  Juan Luis Fernández Gallo and translated by Paulo C. Santos Garcia and Marie-Noëlle Augendre)

  * [Full playlist](https://www.youtube.com/playlist?list=PL8F1F85AC801013BD)

## Tutorial videos in French

There is also a set of French videos available that cover a good part of darktable. Starting by a nice overview and deep into the settings of the darkrooms' modules.

  * [Full playlist](https://www.youtube.com/playlist?list=PLZOdZMT41b7W0IBntprxOOqlw54iiKRMb)

## Tutorials and videos in German

Some nice screencasts for draktable in German. Check them out:

  * [Full playlist](https://vimeo.com/user1479718)

**Comment by paperdigits** [comment]
I've updated the resources page. Please open another issue if there is more to be done.
