### ISSUE TITLE
Broken image links on the english manual

### ISSUE THREAD

**Issue by pphotography** [darktable-org/dtorg#53]
Some image links in the english user manual are broken
Example: 
https://darktable.gitlab.io/doc/en/user_interface.html
The english manual links to this image:
https://darktable.gitlab.io/home/pegelow/darktable/build/doc/usermanual/media/images/lighttable_view.jpg

The french manual links to this image:
https://darktable.gitlab.io/doc/images/lighttable_view.jpg

**Comment by paperdigits** [comment]
This issue is no longer valid. We also now run a link checker on the current manual every commit.
