### ISSUE TITLE
English content in other language manuals

### ISSUE THREAD

**Issue by pphotography** [darktable-org/dtorg#54]
Found english content in the german manual.
- Manual: page 119 and following
- Online: https://darktable.gitlab.io/doc/de/color_group.html

**Comment by pphotography** [comment]
After searching the PDF for the word 'the' I found english phrases on the following pages:
- 40
- 49
- 109
- 111
- 160
- 213 (this is the recommended way...)
- 239
- 242

**Comment by pphotography** [comment]
The italian version has got english on these pages:
- 1 (the powerful...)
- 
- 
- 
- 
- 
- 
-

**Comment by pphotography** [comment]
The italian version has english on these pages:
- 1 (The powerful)
- 6
- 11
- 13
- 23
- 24 ('ordering number'... and 'you can define...'
- 30 (in order for)
- 36
- 40
- 42
- 49
- 50
- 52
- 56
- 58
- 62
- 63
- 64
- 65
- 66
- 71
- 97
- 98
- 99
- 104 - 108
- 109
- 115 - 118
- 124 - 125
- 126
- 127
- 130
- 131
- 135
- 136 - 138
- 143 - 144
- 187
- 193
- 205
- 235
- 238
For the italian translation I recommend to take it from the website until a new version is finished.

**Comment by pphotography** [comment]
The french version has english on these pages:
- 51 (you can hold)
- 61 (This means)

**Comment by patdavid** [comment]
This might be a different project entirely from the main website and can be found here:

https://gitlab.com/darktable/doc

Might get better responses from the team there.

**Comment by mpaglia0** [comment]
> 
> 
> The italian version has english on these pages:
> 
>     * 1 (The powerful)
> 
>     * 6
> 
>     * 11
> 
>     * 13
> 
>     * 23
> 
>     * 24 ('ordering number'... and 'you can define...'
> 
>     * 30 (in order for)
> 
>     * 36
> 
>     * 40
> 
>     * 42
> 
>     * 49
> 
>     * 50
> 
>     * 52
> 
>     * 56
> 
>     * 58
> 
>     * 62
> 
>     * 63
> 
>     * 64
> 
>     * 65
> 
>     * 66
> 
>     * 71
> 
>     * 97
> 
>     * 98
> 
>     * 99
> 
>     * 104 - 108
> 
>     * 109
> 
>     * 115 - 118
> 
>     * 124 - 125
> 
>     * 126
> 
>     * 127
> 
>     * 130
> 
>     * 131
> 
>     * 135
> 
>     * 136 - 138
> 
>     * 143 - 144
> 
>     * 187
> 
>     * 193
> 
>     * 205
> 
>     * 235
> 
>     * 238
>       For the italian translation I recommend to take it from the website until a new version is finished.

I sent the complete .po months ago but noted the same issue (Italian version).
The proof is that PDF manual is completely translated.

**Comment by paperdigits** [comment]
The complete user manual is not fully translated to many langues, and where it isn't translated, the English shows up. I had looked at it a month or so ago, and only the French translation seemed reasonably up-to-date.

**Comment by paperdigits** [comment]
This issue is no longer valid. We're translating the user manual now at https://weblate.pixls.us please help if you can.
