### ISSUE TITLE
Update Darktable logo in website header and favicon

### ISSUE THREAD

**Issue by pphotography** [darktable-org/dtorg#56]
The website shows outdated Darktable logos:

- Main logo on the upper left corner of the screen
- Favicon, shows a grey "dt"

Both should be updated to the current Darktable logo
https://github.com/darktable-org/darktable/blob/master/data/pixmaps/scalable/darktable.svg

**Comment by patdavid** [comment]
I'll just need to generate a new logo/title combo to replace them.
Should the favicon be the logo now?

**Comment by Nilvus** [comment]
@TurboGit : this could be closed as your #86 PR will fix it.

**Comment by TurboGit** [comment]
Sure, but I can't close this one. I'm not super user here. @pphotography : can you close? Thanks.

**Comment by pphotography** [comment]
sure
