### ISSUE TITLE
Search doesn't work on these pages

### ISSUE THREAD

**Issue by afr-e** [darktable-org/dtorg#78]
I only checked these four:
https://darktable.gitlab.io/doc/en/
https://darktable.gitlab.io/doc/fr/
https://darktable.gitlab.io/doc/de/
https://darktable.gitlab.io/doc/it/

Sends me here:
https://gitlab.com/users/sign_in

**Comment by patdavid** [comment]
Yep, the docs are actually a separate beast and not indexed by the search system we use for the main site.

**Comment by moy** [comment]
The manual is not indexed and that would probably be very hard to change, but right now there is a search box on the header of the manual that is indeed useless: searching for anything redirects to `https://darktable.gitlab.io/search.html?q=<search-string>`, which itself redirects to GitLab's login page.

Changing the search box to 

```
<form id="searchform" action="//darktable.org/search.html">
...
</form>
```

(i.e. make `action="..."` absolute) in the usermanual generated pages would fix that (although the search would still search only outside the manual).

**Comment by patdavid** [comment]
Perhaps it would be better to remove the search bar from the docs pages?

**Comment by moy** [comment]
That would work for me too, but if you consider the header to be the header of "the darktable website", not "the darktable user manual", it makes sense to have the same header on all pages, and search site-wide anyway. No strong opinion from me.

**Comment by afr-e** [comment]
I would expect a site-wide search. It is odd to have to use a search engine when there is an onsite search field.

**Comment by paperdigits** [comment]
Search now works in the docs. While it still isn't a site-wide search, we're working on it.
