### ISSUE TITLE
No thumbs images for new 3.0 article in blog and 3.0.0 release on news page

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/dtorg#88]
@patdavid: Just as the title, go on news page and blog page and see that there no automatically generated thumb image.

**Comment by Nilvus** [comment]
@patdavid: what about thumbnails not created for last news articles. On what I test on local machines, python script doesn't update anymore new thumbnails (on local machine, all news and blog articles doesn't have thumb images generated. Seems to have a problem with image_links (and image_compare) scripts. When launching image_links.py script, I have this error:

`Traceback (most recent call last):
  File "plugins/image_compare/image_compare.py", line 22, in <module>
    from . pelican_image_compare_markdown_extension import PelicanImageCompareMarkdownExtension
ValueError: Attempted relative import in non-package
`

**Comment by patdavid** [comment]
From running locally, it appears to possibly be a problem with pillow:

```
...
-> Copying \Personal\github\dtorg\content\images\team\parafin.png to images/team/parafin.png
-> Copying \Personal\github\dtorg\content\images\team\patdavid.jpg to images/team/patdavid.jpg
-> Copying \Personal\github\dtorg\content\images\team\pegelow.jpg to images/team/pegelow.jpg
-> Copying \Personal\github\dtorg\content\images\team\peterbud.jpg to images/team/peterbud.jpg
-> Copying \Personal\github\dtorg\content\images\team\pmjdebruijn.png to images/team/pmjdebruijn.png
-> Copying \Personal\github\dtorg\content\images\team\schenlap.jpg to images/team/schenlap.jpg
CRITICAL: ValueError: Decompressed Data Too Large
Twitter credentials not configured
```

(Note the `CRITICAL` error).  This seems like it might have something to do with decompressing images and possibly with metadata attached?  I'm not sure _which_ image might be causing this problem yet.

**Comment by Nilvus** [comment]
@patdavid: Yes, I also see that and tried to find which image. It's seems that not the two added by last release because I've same error with or without them and I've tried with metadata removed from both. So quite strange and just make news and blog pages quite awful without thumbs images. Locally, all thumbs image are not generated.

**Comment by patdavid** [comment]
Ok, I've tracked down the culprit files this evening.  There were two:

```
/content/blog/2019-12-24-darktable-3.0/en/basicadjustmentsC_L_S.png
/content/blog/2019-12-24-darktable-3.0/en/basicadjustmentsexposition.png
```
I've stripped the exif data from them and we are building fine now...

**Comment by Nilvus** [comment]
> Ok, I've tracked down the culprit files this evening. There were two:
> 
> ```
> /content/blog/2019-12-24-darktable-3.0/en/basicadjustmentsC_L_S.png
> /content/blog/2019-12-24-darktable-3.0/en/basicadjustmentsexposition.png
> ```
> 
> I've stripped the exif data from them and we are building fine now...

Great. Thanks.
