### ISSUE TITLE
Python 2.7 EOL

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/dtorg#95]
Python 2.7 is EOL and can't be installed on Fedora 31.

**Comment by patdavid** [comment]
I'm in the last stages of porting www.gimp.org to py3, and will start working on dt.org when that's done.  Thanks for the heads up. :)

**Comment by Nilvus** [comment]
@patdavid: any news on porting darktable website? I'm writing the 3.2 article to be published in august and I can't now create website on my system (so test all is ok), on Ubuntu 20.04. Of course, I can continue as it's markdown but will not be able to show it in darktable.org way, before publishing my PR.

**Comment by patdavid** [comment]
Sorry for the delay. I’ll get a build up to test what’s failing on py3 and start getting it sorted out.

**Comment by paperdigits** [comment]
We've merged the hugo port to master.
