### ISSUE TITLE
Search results point to old (dt 2.4) docs

### ISSUE THREAD

**Issue by jade-nl** [darktable-org/dtorg#99]
Search results involving darktable point to: https://www.darktable.org/usermanual/en/
Which has the **old 2.4** documentation.

The current location for the **latest** documentation (3.0 atm) is to be found here: https://darktable.gitlab.io/doc/en/

Although a markdown conversion is being done at the moment that will make building the docs on the main darktable site easier it would probably be a good idea to create a redirect from on site to the other.

This will fix:
1.  the immediate problem of people being directed to (very) old documentation
2. make maintenance and consistency more manageable (1 site instead of 2).

PS: I got the hint on IRC that I should ping @patdavid for this.

**Comment by jade-nl** [comment]
Haven't noticed any reactions to this.

This is still an issue and people do run into being pointed to very outdated darktable documents.

Here's a rather recent one that I just noticed: [Where is the Equalizer Module](https://old.reddit.com/r/DarkTable/comments/i7kone/where_is_the_equalizer_module/). The *manual* link points to an old 2.4 doc and users get confused/misinformed.

I'm presuming that search-engine spiders (or whatever they use nowadays) keep running into this and index them. Using DuckDuckGo _always_ points to the ww.darktable.org/usermanual version and there's no hint whatsoever of the  darktable.gitlab.io/doc version.....

Not sure why a redirect, as suggested in the first post, wouldn't be a valid solution.

**Comment by paperdigits** [comment]
I don't like having the docs on a different domain. I'm currently thinking about many docs issues, one of them being how to get the most recent docs back on the main domain.

Do we really need to host older versions of the docs?

**Comment by jade-nl** [comment]
This issue has been fixed after introducing the new 3.4 docs.

Closing this one.
